chore: testing
prisma/templates pull request #18
Opened 2021-08-10 16:31 UTC by ruheni

2021-08-12 17:22 UTC, jasonkuhrt submitted a review, later dismissed

2021-08-12 17:22 UTC, jasonkuhrt commented on .github/scripts/tests/test.spec.ts
> +    execa.commandSync(`rsync -avr --exclude="../../${templateName}/node_modules" ../../${templateName} ../`)
what is this doing

2021-08-12 17:22 UTC, jasonkuhrt commented on .github/scripts/tests/test.spec.ts
> +    execa.commandSync(` yarn ${changeDir}`)
execa can be made to run from a different `cwd`. Then write commands here as if you were in that directory. See third parameter options.

2021-08-12 18:47 UTC, ruheni commented on .github/scripts/tests/test.spec.ts
> +    execa.commandSync(`rsync -avr --exclude="../../${templateName}/node_modules" ../../${templateName} ../`)
For the purpose of running the test locally, this command copies the templates into the `.github` folder (excluding `node_modules`).

2021-08-12 18:54 UTC, ruheni commented on .github/scripts/tsconfig.json
> +      "~/*": ["./*"]
It does! 
![image](https://user-images.githubusercontent.com/33921841/129252629-c2aa39b5-a389-496b-be51-25ba6f98ede4.png)

2021-08-12 18:54 UTC, ruheni commented on .github/scripts/tests/test.spec.ts
> +  test.each(projects)('$templateName', async ({ templateName }) => {
It does! 
![image](https://user-images.githubusercontent.com/33921841/129252629-c2aa39b5-a389-496b-be51-25ba6f98ede4.png)

2021-08-12 18:59 UTC, jasonkuhrt commented on .github/scripts/tests/test.spec.ts
> +    execa.commandSync(`rsync -avr --exclude="../../${templateName}/node_modules" ../../${templateName} ../`)
Why does the project have to be moved.

Run the commands (yarn etc.) inside the directory where the example already exists.

2021-08-13 12:50 UTC, jasonkuhrt requested changes

2021-08-13 12:50 UTC, jasonkuhrt commented on .github/scripts/tests/test.spec.ts
> +    const options = { cwd: `../../${templateName}` }
Put a type annotation on this so we get autocomplete.

2021-08-13 12:50 UTC, jasonkuhrt commented on .github/scripts/tests/test.spec.ts
> +    const options = { cwd: `../../${templateName}` }
Call this `execaConfig`

2021-08-13 12:50 UTC, jasonkuhrt commented on .github/scripts/tests/test.spec.ts
> +    const options = { cwd: `../../${templateName}` }
Alternative is a constant of `cwd` and then thread that down below `, {cwd})`

2021-08-13 12:50 UTC, jasonkuhrt commented on .github/scripts/jest.config.ts
> +      compiler: 'ttypescript',
```suggestion
```

Not needed

2021-08-13 12:50 UTC, jasonkuhrt commented on .github/scripts/jest.config.ts
> +  testEnvironment: 'node',
```suggestion
```

This is the default

2021-08-13 12:50 UTC, jasonkuhrt commented on .github/scripts/package.json
> +    "ttypescript": "^1.5.12",
```suggestion
```

Not needed

2021-08-13 12:50 UTC, jasonkuhrt commented on .github/scripts/tests/test.spec.ts
> +     */
```suggestion
```

Duplicates the code not needed

2021-08-13 12:50 UTC, jasonkuhrt commented on .github/scripts/tsconfig.json
> +  "exclude": ["node_modules", ""],
```suggestion
  "exclude": ["node_modules"],
```

2021-08-13 12:59 UTC, ruheni commented on .github/scripts/tests/test.spec.ts
> +    const options = { cwd: `../../${templateName}` }
Is there a way to add types to the output?

2021-08-13 13:07 UTC, ruheni commented on .github/scripts/tests/test.spec.ts
> +    const options = { cwd: `../../${templateName}` }
Turns out, seeding can fail but return no error, based on the seeding scripts

2021-08-13 13:09 UTC, ruheni commented on .github/scripts/tests/test.spec.ts
> +    const options = { cwd: `../../${templateName}` }
Would modifying the seeding script to exit and log on error help? We currently don't do that

2021-08-13 15:44 UTC, jasonkuhrt commented on .github/scripts/tests/test.spec.ts
> +    const options = { cwd: `../../${templateName}` }
> Turns out, seeding can fail but return no error, based on the seeding scripts

seeding is a script, not a function, I'm not sure what you mean.

> Would modifying the seeding script to exit and log on error help? We currently don't do that

We need to be careful what we do here in case it conflicts with the expectations of the templates package.

Relying on the default Node throw on uncaught error should be sufficient. What's the problem?

2021-08-13 15:48 UTC, ruheni commented on .github/scripts/tests/test.spec.ts
> +    const options = { cwd: `../../${templateName}` }
>seeding is a script, not a function, I'm not sure what you mean.

Sorry, I confused the two

>Relying on the default Node throw on uncaught error should be sufficient. What's the problem?

Node doesn't throw any error when seeding fails

2021-08-13 15:51 UTC, jasonkuhrt commented on .github/scripts/tests/test.spec.ts
> +    const options = { cwd: `../../${templateName}` }
Why not?

2021-08-13 17:52 UTC, jasonkuhrt commented on .github/scripts/tests/test.spec.ts
> +    const seed = execa.commandSync(`yarn ts-node ./prisma/seed.ts`, execaConfig)
```suggestion
    const seed = execa.commandSync(`yarn ts-node prisma/seed`, execaConfig)
```

2021-08-13 17:53 UTC, jasonkuhrt commented
Before merging this PR we should merge the `cloud` branch into `main` and then rebase this PR

2021-08-13 19:10 UTC, jasonkuhrt commented
#21

2021-08-13 23:02 UTC, jasonkuhrt requested changes

2021-08-13 23:02 UTC, jasonkuhrt commented on rentalsPlatform/prisma/seed.ts
> +seed()
This breaks the templates package I think

Adjust your `ts-node` code to a require of this seed file and then invoke the seed function.

2021-08-21 20:31 UTC, jasonkuhrt commented on .github/scripts/tests/test.spec.ts
> +    const seed = execa.commandSync(`yarn ts-node -r ./prisma/seed.ts`, execaConfig)
Don't you need to call `seed` function here?

2021-09-04 16:52 UTC, ruheni commented on .github/scripts/tests/test.spec.ts
> +    const seed = execa.commandSync(`yarn ts-node -r ./prisma/seed.ts`, execaConfig)
This should be resolved now

2021-09-04 16:57 UTC, ruheni commented on .github/scripts/tests/test.spec.ts
> +    const seed = execa.commandSync(`yarn ts-node -r ./prisma/seed.ts`, execaConfig)
Ran into some errors, will go ahead and fix it

2021-09-04 18:37 UTC, jasonkuhrt commented on rentalsPlatform/prisma/seed.ts
> +    for (let room of rooms) {
Can this be parallel?

If so then do this:

```ts
await prisma.$transaction(rooms.map(room => prisma.room.create(...))
```

2021-09-04 18:39 UTC, jasonkuhrt commented on rentalsPlatform/prisma/seed.ts
>      for (let entry of data) {
And you can add this to above I think

```ts
await prisma.$transaction([
  ...rooms.map(room => prisma.room.create(...)
  ...data.map(entry => prisma.user.create(...))
])
```

2021-09-04 18:40 UTC, jasonkuhrt commented on rentalsPlatform/prisma/seed.ts
>      for (let entry of data) {
While you're here, maybe fix variable name `data` that name is almost meaningless.

2021-09-04 20:44 UTC, ruheni commented on rentalsPlatform/prisma/seed.ts
>      for (let entry of data) {
Renamed `data` to `users`.

Reservations are dependent on rooms and in this case, transactions won't be a good fit

2021-09-04 20:50 UTC, jasonkuhrt commented on .github/scripts/tests/test.spec.ts
> +    execa.commandSync(` yarn`, execaConfig)
```suggestion
    execa.commandSync(`yarn`, execaConfig)
```

2021-09-04 20:51 UTC, jasonkuhrt approved these changes
LGTM

Just get the tests actually passing :)

2021-09-08 17:45 UTC, jasonkuhrt requested changes
can simplify this

2021-09-08 17:45 UTC, jasonkuhrt commented on urlShortener/package.json
> +    "seed": "ts-node ./prisma/seed.ts"
```suggestion
    "seed": "ts-node prisma/seed"
```

2021-09-08 18:01 UTC, merged